### ISSUE TITLE
Improved project-subtitle?

### ISSUE THREAD

**Issue by davidrpugh** [EconomicSL/EconomicSL.github.io#7]
I think we can improve upon "A library for modelling economic systems".  First, we are developing several libraries, not just one.  More fundamentally, I don't think this sub-title is getting across what I think are the main contributions of the project.  Something like...

"Open-Source Economic Simulation for Java and Scala."

Thoughts?

**Comment by KG-ethc** [comment]
I agree, some work needs to be done here. I searched for many days on Github, Google, Wikipedia, ECB, Santa Fe Institute, etc. trying to find any current open source (and non-open source) simulations. I searched ABM, ABM spelled out, ABM Java, Economic simulations, and then finally yesterday I found a link on Dr. Farmer's Santa Fe page to CRISIS, which I found to be an inactive project, and then I emailed him and he let me know about this site. (Thank you!)

Things that might help:
Mention on CRISIS that it's been deprecated or superseeded by this?
Try to add the project to this wikipedia page unless you think it's not ready: https://en.wikipedia.org/wiki/Comparison_of_agent-based_modeling_software
Update your Bio's to include EconomicSL
Update Dr. Farmer's (and anyone else's) wikipedia page to reference this project.
Update Santa Fe institute's pages to reference ESL.
Ask your friends/universities to link to the site.

I think the subtitle is OK, but title>Economic Simulation Library</ti on https://economicsl.github.io/ should be a lot more verbose, and should definitely include Java and Scala.

**Comment by davidrpugh** [comment]
@KG-ethc Thanks for the feedback!  One possible improved subtitle would shamelessly borrow from [DeepLearning4j](https://deeplearning4j.org/)...

"Open-Source, Distributed, Economic Simulation Libraries for Java and Scala"

...however we believe that the core abstractions necessary for doing sensible large-scale economic simulation modeling are independent of the implementation language in which this abstractions are implemented and we would like to encourage contributions to the design of our core APIs from researchers who might be more used to working in other languages such as Python.

Thus perhaps more inclusive tag-line would be something like...

"An Open-Source, Economics-Specific Language for Distributed Simulation Modeling"

...are either of these an improvement?

**Comment by adrian-carro** [comment]
Website no longer maintained and to be closed down. Closing all open issues.
